<?php

use Simple\Template;

//<!-- set template used as base for current view-->
Template::SetBase(__DIR__ . '/../../base.phtml');

//<!-- set partials included with current view -->
Template::Partials([__DIR__ . '/../../layout/header.phtml', __DIR__ . '/../../layout/footer.phtml']);

//<!-- section example  using pure php -->
Template::SectionContent('title', function (array $post = null, bool $edit = false) {
    echo ($edit ? 'Editing - ' : '') . $post['title'] ?? 'Unknown';
});

Template::SectionContent('content', function (array $post = null, bool $edit = false) {
    $user = $_SESSION['user'] ?? null;

    if ($edit && ($user['id'] ?? null) === (int) $post['user_id']) {
        require_once __DIR__ . '/views/edit.phtml';

        return;
    }

    require_once __DIR__ . '/views/view.phtml';
});
